# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ScholarlyInfrastructure',
                'doc_host': 'https://THU-CVML.github.io',
                'git_url': 'https://github.com/THU-CVML/ScholarlyInfrastructure',
                'lib_path': 'scholarly_infrastructure'},
  'syms': { 'scholarly_infrastructure.nucleus': { 'scholarly_infrastructure.nucleus.foo': ( 'nucleus (core functionalities of this lib) '
                                                                                            '.html#foo',
                                                                                            'scholarly_infrastructure/nucleus.py')}}}
