"""core functionalities of this lib"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_nucleus (other infras).ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../notebooks/00_nucleus (other infras).ipynb 3
def foo(): pass
